#pragma once

namespace ascii_character {

enum ParamId {
    PARAM_INPUT = 0,
    PARAM_PIXEL_DENSITY,
    PARAM_CELL_ASPECT,
    PARAM_CHARACTER_SCALE,
    PARAM_SPACING_X,
    PARAM_SPACING_Y,
    PARAM_BLEND_ORIGINAL,
    PARAM_PRESERVE_ALPHA,
    PARAM_INVERT_LUMINANCE,
    PARAM_CONTRAST,
    PARAM_BRIGHTNESS,
    PARAM_GAMMA,
    PARAM_THRESHOLD,
    PARAM_POSTERIZE,
    PARAM_CHARACTER_SET,
    PARAM_CHARACTER_ORDER,
    PARAM_COLOR_MODE,
    PARAM_FOREGROUND,
    PARAM_BACKGROUND,
    PARAM_GRADIENT_START,
    PARAM_GRADIENT_END,
    PARAM_HUE_SHIFT,
    PARAM_SATURATION,
    PARAM_HORIZONTAL_ALIGN,
    PARAM_VERTICAL_ALIGN,
    PARAM_OFFSET_X,
    PARAM_OFFSET_Y,
    PARAM_ROTATION,
    PARAM_QUALITY,
    PARAM_ANTIALIAS,
    PARAM_NTH_CELL,
    PARAM_COUNT
};

} // namespace ascii_character
