import argparse
import sys
from PIL import Image, ImageDraw, ImageFont

def main():
    parser = argparse.ArgumentParser(description="Generate After Effects ASCII glyph atlas header")
    parser.add_argument("--font", required=True, help="Path to TTF font file")
    parser.add_argument("--font-size", type=int, default=18, help="Font size to render")
    parser.add_argument("--cell-width", type=int, default=16, help="Width of each glyph cell")
    parser.add_argument("--cell-height", type=int, default=24, help="Height of each glyph cell")
    parser.add_argument("--output", required=True, help="Path to output C++ header file")
    args = parser.parse_args()

    try:
        font = ImageFont.truetype(args.font, args.font_size)
    except Exception as e:
        print(f"Error loading font {args.font}: {e}", file=sys.stderr)
        sys.exit(1)

    first_glyph = 32  # Space
    last_glyph = 126   # Tilde ~
    num_glyphs = last_glyph - first_glyph + 1

    # Store flat pixel coverage
    coverage_data = []

    for c in range(first_glyph, last_glyph + 1):
        char = chr(c)
        # Create a single-channel grayscale image for the cell
        img = Image.new("L", (args.cell_width, args.cell_height), 0)
        draw = ImageDraw.Draw(img)
        
        # Draw the character centered using middle-middle (mm) anchor
        # This keeps the baseline and alignments consistent
        x = args.cell_width / 2.0
        y = args.cell_height / 2.0
        draw.text((x, y), char, font=font, fill=255, anchor="mm")

        # Collect raw byte data
        pixels = list(img.getdata())
        coverage_data.extend(pixels)

    # Format C++ output
    with open(args.output, "w") as f:
        f.write("// Generated by generate_glyph_atlas.py. DO NOT EDIT.\n")
        f.write("#pragma once\n\n")
        f.write("namespace ascii_character {\n\n")
        f.write(f"constexpr int kGlyphWidth = {args.cell_width};\n")
        f.write(f"constexpr int kGlyphHeight = {args.cell_height};\n")
        f.write(f"constexpr int kFirstGlyph = {first_glyph};\n")
        f.write(f"constexpr int kLastGlyph = {last_glyph};\n")
        f.write(f"constexpr int kGlyphCount = {num_glyphs};\n\n")
        
        f.write("constexpr unsigned char kGlyphCoverage[] = {\n")
        # Format bytes as 16 hex values per line for readability
        for i in range(0, len(coverage_data), 16):
            chunk = coverage_data[i:i+16]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            f.write(f"    {hex_str},\n" if i + 16 < len(coverage_data) else f"    {hex_str}\n")
        f.write("};\n\n")
        f.write("} // namespace ascii_character\n")

    print(f"Successfully generated glyph atlas at {args.output}")

if __name__ == "__main__":
    main()
